version: '3'

services:

  mariadb:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=kodi
      - TZ=Pacific/Auckland
    ports:
      - 3306:3306

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_HOST=kodi-mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=kodi
      - TZ=Pacific/Auckland
    ports:
      - 8080:8080
      - 9090:9090
      - 9777:9777/udp